blank_issues_enabled: true
contact_links:
  - name: 纯纯看番社区
    url: https://github.com/orgs/easybangumiorg/discussions
    about: 可以在这里看看是否有人遇到了相同的问题
  - name: QQ频道
    url: https://pd.qq.com/s/4q8rd0285
    about: 从QQ频道发起讨论或是加入群
  - name: Telegram
    url: https://t.me/easy_bangumi
    about: 从Tg群聊发起讨论
